config/routes.rb
RottenMangoes::Application.routes.draw do

  get 'reviews/new'

  get 'reviews/create'

  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  namespace :admin do
    resources :users do
      get  :switch
    end
  end

  resources :users do
    get :switch_back
  end

  resource :session, only: [:new, :create, :destroy]
  root to: 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :reviews

  validates :title, :director, :description, :release_date, presence: true
  validates :runtime_in_minutes, numericality: { only_integer: true }
  validate :release_date_is_in_the_past

  mount_uploader :image, ImageUploader

  scope :title, -> (text) { where 'title like ?', text}
  scope :title_and_director, -> (tit, dir) {title(tit).where('director like ?', dir)}

  def review_average
    reviews.sum(:rating_out_of_ten)/reviews.size if reviews.size > 0
  end

  def self.runtime_in_range(min)
    max = 90 if min == 0
    max = 120 if min == 90
    max = 9999 if min == 120 or min == -1
    where('runtime_in_minutes >= ? and runtime_in_minutes < ?', min, max)
  end

  protected

  def release_date_is_in_the_past
    if release_date.present?
      errors.add(:release_date, "should be in the past") if release_date > Date.today
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :movie

  validates :user, :movie, :text, presence: true

  validates :rating_out_of_ten, numericality: {only_integer: true}
  validates :rating_out_of_ten, numericality: {greater_than_or_equal_to: 1}
  validates :rating_out_of_ten, numericality: {less_than_or_equal_to: 10}

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews, dependent: :destroy

  validates :email, :firstname, :lastname, presence: true
  has_secure_password

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :check_admin

  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "#{@user.fullname} added"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def switch
    switch_to(params[:user_id])
    redirect_to movies_path
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname)
  end

  def check_admin
    redirect_to root_url, notice: "Cannot view unless admin" unless current_user.admin
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def switch_to(user_id)
    if @current_user.admin
      session[:prev_id] = current_user.id
      session[:user_id] = user_id.to_i
    end
  end

  def switch_back_to_admin
      session[:user_id] = session[:prev_id]
      session[:prev_id] = nil
  end

  helper_method :current_user
  helper_method :switch_to_user
  helper_method :switch_back_to_admin

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    if input = params[:movie]
      title = "%#{input[:title]}%"
      director = "%#{input[:director]}%"
      @movies = Movie.title_and_director(title, director).runtime_in_range(input[:runtime_in_minutes].to_i)
    else
      @movies = Movie.all
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(:title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description, :image, :remote_image_url)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :restrict_access, :load_movie

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      unless current_user && current_user.admin
        session[:user_id] = @user.id
        redirect_to users_path, notice: "Welcome aboard, #{@user.firstname}!"
      else
        redirect_to users_path, notice: "Created user #{@user.firstname}"
      end
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    UserMailer.delete_confirmation(@user).deliver
    @user.destroy
    session.clear if params[:id] == session[:id]
    redirect_to users_path
  end

  def switch_back
    switch_back_to_admin
    redirect_to users_path
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    User.find(session[:user_id])
  end

end

app/helpers/movies_helper.rb
module MoviesHelper
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<h1>Rotten Mangoes</h1>
<h2>Users</h2>
<%= paginate @users %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Admin Status</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.email%></td>
        <td> <%= user.admin %></td>
        <td><% if current_user and current_user.admin  %>
          <%= link_to "edit", edit_user_path(user) %> | <%= link_to "switch to user", admin_user_switch_path(user) %> | <%= link_to "delete", user_path(user), method: :delete, confirm: "You sure?" %>
        <% end %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
      <% if session[:prev_id] %>
         <%= link_to "switch back", user_switch_back_path(current_user.id) %>
      <% end  %>
      <% if current_user.admin %>
        <%= link_to "Users List", admin_users_path %> | <%= link_to "Create A User", new_user_path %>
      <% end %>
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
    <% console %>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value) %>
    <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, :html => {:multipart => true} do |f| %>

  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :release_date %><br>
    <%= f.date_field :release_date %>
  </div>
  <div>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div>
    <%= f.label :runtime_in_minutes %><br>
    <%= f.number_field :runtime_in_minutes %>
  </div>
  <div>
    <%= f.label :remote_image_url, "or image url" %><br>
    <%= f.text_field :remote_image_url %>
  </div>
  <div>
    <%= f.file_field :image %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<% movies.each do |movie| %>
  <%= link_to image_tag(movie.poster_image_url), movie_path(movie) %>
  <h2><%= link_to movie.title, movie_path(movie) %></h2>
  <h3><%= movie.review_average %>/10</h3>
  <h3><%= movie.release_date %></h3>
  <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
  <p><%= movie.description %></p>
<% end %>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2> Edit this movie.</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Rotten Mangoes</h1>

<%= form_for :movie, url: movies_path, method: :get do |f|%>
  <p>
    <%= f.label :title %>
    <%= f.text_field 'title', value: params[:title] %>
    <%= f.label :director %>
    <%= f.text_field 'director', value: params[:director] %>
    <%= f.label :runtime_in_minutes %>
    <%= f.select(:runtime_in_minutes, [['no range', -1], ['less than 90 min', 0], ['between 90 and 120 minutes', 90], ['greater than 120 minutes', 120]]) %>
    <%= f.submit "search", name: nil %>
  </p>
<% end %>

<%= link_to "Submit a movie!", new_movie_path %>
<%= render partial: 'movie', locals: {movies: @movies} %>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2> Submit a movie!</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>

<%= link_to image_tag(@movie.image_url(:thumb)), movie_path(@movie) %>
<h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>) | <%= @movie.review_average %>/10</h2>
<h3><%= formatted_date(@movie.release_date) %></h3>
<h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
<p><%= @movie.description %></p>

<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <%= review.user.full_name %></small><br/>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :text %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.label :rating_out_of_ten %><br>
    <%= f.number_field :rating_out_of_ten %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, :html => {:multipart => true} do |f| %>

  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented this user from being submitted:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <% if current_user.admin %>
    <div>
      <%= f.label :admin, "Admin" %><br>
      <%= f.check_box :admin %>
    </div>
  <% end %>
  <% if current_user == @user %>
    <div>
      <%= f.label :password, "New Password" %><br>
      <%= f.text_field :password %>
    </div>
  <% end %>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/edit.html.erb
<%= link_to "Back to this user", user_path(@user) %>
<h1>Edit User <%= @user.full_name %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<%= link_to "Back to all movies", movies_path %><br/>
<h1>Rotten Mangoes</h1>
<h2>Users</h2>
<%= paginate @users %>
<tbody>
  <% @users.each do |user| %>
    <tr>
      <th><%= user.full_name %></th>
      <th><%= user.email%></th>
      <th> <%= user.admin %></th>
      <% if current_user and current_user.admin  %>
        <%= link_to "edit", edit_user_path(user) %> | <%= link_to "switch to user", admin_user_switch_path(user) %> | <%= link_to "delete", user_path(user), method: :delete, confirm: "You sure?" %>
      <% end %>
    </tr>
  <% end %>
</tbody>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/show.html.erb
<%= link_to "Back to all users", users_path %><br/>

<h3><%= @user.full_name %></h3>
<h5><%= (@user.email)%></h5>
<% if current_user.admin  %>
  <%= link_to "edit", edit_user_path(@user) %> | <%= link_to "delete", user_path(@user), method: :delete, confirm: "You sure?" %>
<% end %>